/* AcneSafeCheck — comedogenicity engine + database (auto-generated). rating 0..5. */
const DB = [
  {"n": "Algae Extract", "r": 5, "c": "Marine", "a": ["algae", "algae extract"], "s": "algae-extract", "fa": false},
  {"n": "Carrageenan", "r": 5, "c": "Thickener", "a": ["carrageenan", "chondrus crispus"], "s": "carrageenan", "fa": false},
  {"n": "Hexadecyl Alcohol", "r": 5, "c": "Fatty alcohol", "a": ["hexadecyl alcohol"], "s": "hexadecyl-alcohol", "fa": true},
  {"n": "Isocetyl Stearate", "r": 5, "c": "Ester", "a": ["isocetyl stearate"], "s": "isocetyl-stearate", "fa": true},
  {"n": "Isopropyl Isostearate", "r": 5, "c": "Ester", "a": ["isopropyl isostearate"], "s": "isopropyl-isostearate", "fa": true},
  {"n": "Isopropyl Linoleate", "r": 5, "c": "Ester", "a": ["isopropyl linoleate"], "s": "isopropyl-linoleate", "fa": true},
  {"n": "Isopropyl Myristate", "r": 5, "c": "Ester", "a": ["isopropyl myristate"], "s": "isopropyl-myristate", "fa": true},
  {"n": "Laureth-4", "r": 5, "c": "Emulsifier", "a": ["laureth 4", "laureth-4"], "s": "laureth-4", "fa": true},
  {"n": "Myristyl Myristate", "r": 5, "c": "Ester", "a": ["myristyl myristate"], "s": "myristyl-myristate", "fa": true},
  {"n": "Octyl Stearate", "r": 5, "c": "Ester", "a": ["ethylhexyl stearate", "octyl stearate"], "s": "octyl-stearate", "fa": true},
  {"n": "Red Algae", "r": 5, "c": "Marine", "a": ["red algae"], "s": "red-algae", "fa": false},
  {"n": "Sodium Lauryl Sulfate", "r": 5, "c": "Surfactant", "a": ["sls", "sodium lauryl sulfate"], "s": "sodium-lauryl-sulfate", "fa": false},
  {"n": "Wheat Germ Oil", "r": 5, "c": "Oil", "a": ["triticum vulgare germ oil", "wheat germ oil"], "s": "wheat-germ-oil", "fa": true},
  {"n": "Acetylated Lanolin", "r": 4, "c": "Occlusive", "a": ["acetylated lanolin"], "s": "acetylated-lanolin", "fa": false},
  {"n": "Acetylated Lanolin Alcohol", "r": 4, "c": "Occlusive", "a": ["acetylated lanolin alcohol"], "s": "acetylated-lanolin-alcohol", "fa": false},
  {"n": "Algin", "r": 4, "c": "Thickener", "a": ["algin"], "s": "algin", "fa": false},
  {"n": "Ceteareth-20", "r": 4, "c": "Emulsifier", "a": ["ceteareth-20", "cetearyl alcohol ceteareth-20"], "s": "ceteareth-20", "fa": true},
  {"n": "Cocoa Butter", "r": 4, "c": "Butter", "a": ["cocoa butter", "theobroma cacao", "theobroma cacao seed butter"], "s": "cocoa-butter", "fa": true},
  {"n": "Coconut Butter", "r": 4, "c": "Butter", "a": ["coconut butter"], "s": "coconut-butter", "fa": true},
  {"n": "Coconut Oil", "r": 4, "c": "Oil", "a": ["coconut oil", "cocos nucifera oil"], "s": "coconut-oil", "fa": true},
  {"n": "Isopropyl Palmitate", "r": 4, "c": "Ester", "a": ["isopropyl palmitate"], "s": "isopropyl-palmitate", "fa": true},
  {"n": "Isostearyl Isostearate", "r": 4, "c": "Ester", "a": ["isostearyl isostearate"], "s": "isostearyl-isostearate", "fa": true},
  {"n": "Isostearyl Neopentanoate", "r": 4, "c": "Ester", "a": ["isostearyl neopentanoate"], "s": "isostearyl-neopentanoate", "fa": true},
  {"n": "Laminaria Digitata Extract", "r": 4, "c": "Marine", "a": ["laminaria digitata extract"], "s": "laminaria-digitata-extract", "fa": false},
  {"n": "Lauric Acid", "r": 4, "c": "Fatty acid", "a": ["lauric acid"], "s": "lauric-acid", "fa": true},
  {"n": "Lecithin", "r": 4, "c": "Emulsifier", "a": ["lecithin"], "s": "lecithin", "fa": true},
  {"n": "Linseed / Flaxseed Oil", "r": 4, "c": "Oil", "a": ["flaxseed oil", "linseed oil", "linum usitatissimum seed oil"], "s": "linseed-flaxseed-oil", "fa": true},
  {"n": "Myristyl Lactate", "r": 4, "c": "Ester", "a": ["myristyl lactate"], "s": "myristyl-lactate", "fa": true},
  {"n": "Octyl Palmitate", "r": 4, "c": "Ester", "a": ["ethylhexyl palmitate", "octyl palmitate"], "s": "octyl-palmitate", "fa": true},
  {"n": "PEG-16 Lanolin", "r": 4, "c": "Emulsifier", "a": ["peg 16 lanolin", "peg-16 lanolin"], "s": "peg-16-lanolin", "fa": false},
  {"n": "Polyglyceryl-3 Diisostearate", "r": 4, "c": "Emulsifier", "a": ["polyglyceryl-3 diisostearate"], "s": "polyglyceryl-3-diisostearate", "fa": true},
  {"n": "Steareth-10", "r": 4, "c": "Emulsifier", "a": ["steareth-10"], "s": "steareth-10", "fa": true},
  {"n": "Avocado Oil", "r": 3, "c": "Oil", "a": ["avocado oil", "persea gratissima oil"], "s": "avocado-oil", "fa": true},
  {"n": "Butyl Stearate", "r": 3, "c": "Ester", "a": ["butyl stearate"], "s": "butyl-stearate", "fa": true},
  {"n": "Cetyl Acetate", "r": 3, "c": "Ester", "a": ["cetyl acetate"], "s": "cetyl-acetate", "fa": true},
  {"n": "Coconut Alkanes", "r": 3, "c": "Oil", "a": ["coconut alkanes"], "s": "coconut-alkanes", "fa": false},
  {"n": "Corn Oil", "r": 3, "c": "Oil", "a": ["corn oil", "zea mays oil"], "s": "corn-oil", "fa": true},
  {"n": "Cotton Seed Oil", "r": 3, "c": "Oil", "a": ["cotton seed oil", "cottonseed oil", "gossypium oil"], "s": "cotton-seed-oil", "fa": true},
  {"n": "D&C Red 17", "r": 3, "c": "Colorant", "a": ["d&c red 17", "red 17"], "s": "d-c-red-17", "fa": false},
  {"n": "D&C Red 21", "r": 3, "c": "Colorant", "a": ["d&c red 21", "red 21"], "s": "d-c-red-21", "fa": false},
  {"n": "D&C Red 30", "r": 3, "c": "Colorant", "a": ["d&c red 30", "red 30"], "s": "d-c-red-30", "fa": false},
  {"n": "D&C Red 36", "r": 3, "c": "Colorant", "a": ["d&c red 36", "red 36"], "s": "d-c-red-36", "fa": false},
  {"n": "D&C Red 6", "r": 3, "c": "Colorant", "a": ["ci 15850", "d&c red 6", "red 6"], "s": "d-c-red-6", "fa": false},
  {"n": "D&C Red 7", "r": 3, "c": "Colorant", "a": ["d&c red 7", "red 7"], "s": "d-c-red-7", "fa": false},
  {"n": "D&C Red 9", "r": 3, "c": "Colorant", "a": ["d&c red 9", "red 9"], "s": "d-c-red-9", "fa": false},
  {"n": "Decyl Oleate", "r": 3, "c": "Ester", "a": ["decyl oleate"], "s": "decyl-oleate", "fa": true},
  {"n": "Glyceryl Stearate SE", "r": 3, "c": "Ester", "a": ["glyceryl stearate se"], "s": "glyceryl-stearate-se", "fa": true},
  {"n": "Laureth-23", "r": 3, "c": "Emulsifier", "a": ["laureth-23"], "s": "laureth-23", "fa": true},
  {"n": "Mink Oil", "r": 3, "c": "Oil", "a": ["mink oil"], "s": "mink-oil", "fa": true},
  {"n": "Myristic Acid", "r": 3, "c": "Fatty acid", "a": ["myristic acid"], "s": "myristic-acid", "fa": true},
  {"n": "PEG-8 Stearate", "r": 3, "c": "Emulsifier", "a": ["peg 8 stearate", "peg-8 stearate"], "s": "peg-8-stearate", "fa": true},
  {"n": "PPG-2 Myristyl Ether Propionate", "r": 3, "c": "Ester", "a": ["ppg-2 myristyl ether propionate"], "s": "ppg-2-myristyl-ether-propionate", "fa": true},
  {"n": "Sesame Oil", "r": 3, "c": "Oil", "a": ["sesame oil", "sesamum indicum seed oil"], "s": "sesame-oil", "fa": true},
  {"n": "Shark Liver Oil", "r": 3, "c": "Oil", "a": ["shark liver oil"], "s": "shark-liver-oil", "fa": true},
  {"n": "Sodium Laureth Sulfate", "r": 3, "c": "Surfactant", "a": ["sles", "sodium laureth sulfate"], "s": "sodium-laureth-sulfate", "fa": true},
  {"n": "Sorbitan Oleate", "r": 3, "c": "Emulsifier", "a": ["sorbitan oleate"], "s": "sorbitan-oleate", "fa": true},
  {"n": "Sorbitan Sesquioleate", "r": 3, "c": "Emulsifier", "a": ["sorbitan sesquioleate"], "s": "sorbitan-sesquioleate", "fa": true},
  {"n": "Soybean Oil", "r": 3, "c": "Oil", "a": ["glycine soja oil", "soybean oil"], "s": "soybean-oil", "fa": true},
  {"n": "Spearmint Oil", "r": 3, "c": "Essential oil", "a": ["mentha viridis leaf oil", "spearmint oil"], "s": "spearmint-oil", "fa": false},
  {"n": "Wheat Germ Glyceride", "r": 3, "c": "Oil", "a": ["wheat germ glyceride"], "s": "wheat-germ-glyceride", "fa": true},
  {"n": "Apricot Kernel Oil", "r": 2, "c": "Oil", "a": ["apricot kernel oil", "prunus armeniaca kernel oil"], "s": "apricot-kernel-oil", "fa": true},
  {"n": "Beeswax", "r": 2, "c": "Wax", "a": ["beeswax", "cera alba"], "s": "beeswax", "fa": false},
  {"n": "Borage Oil", "r": 2, "c": "Oil", "a": ["borage oil", "borago officinalis seed oil"], "s": "borage-oil", "fa": true},
  {"n": "Ceteareth-25", "r": 2, "c": "Emulsifier", "a": ["ceteareth-25"], "s": "ceteareth-25", "fa": true},
  {"n": "Cetearyl Alcohol", "r": 2, "c": "Fatty alcohol", "a": ["cetearyl alcohol"], "s": "cetearyl-alcohol", "fa": true},
  {"n": "Cetyl Alcohol", "r": 2, "c": "Fatty alcohol", "a": ["cetyl alcohol"], "s": "cetyl-alcohol", "fa": true},
  {"n": "D&C Red 27", "r": 2, "c": "Colorant", "a": ["d&c red 27", "red 27"], "s": "d-c-red-27", "fa": false},
  {"n": "D&C Red 33", "r": 2, "c": "Colorant", "a": ["d&c red 33", "red 33"], "s": "d-c-red-33", "fa": false},
  {"n": "Evening Primrose Oil", "r": 2, "c": "Oil", "a": ["evening primrose oil", "oenothera biennis oil"], "s": "evening-primrose-oil", "fa": true},
  {"n": "Glyceryl Oleate", "r": 2, "c": "Ester", "a": ["glyceryl oleate"], "s": "glyceryl-oleate", "fa": true},
  {"n": "Jojoba Oil", "r": 2, "c": "Oil", "a": ["jojoba oil", "simmondsia chinensis seed oil"], "s": "jojoba-oil", "fa": true},
  {"n": "Lanolin", "r": 2, "c": "Occlusive", "a": ["lanolin"], "s": "lanolin", "fa": false},
  {"n": "Lanolin Alcohol", "r": 2, "c": "Occlusive", "a": ["lanolin alcohol"], "s": "lanolin-alcohol", "fa": false},
  {"n": "Macadamia Oil", "r": 2, "c": "Oil", "a": ["macadamia integrifolia seed oil", "macadamia oil"], "s": "macadamia-oil", "fa": true},
  {"n": "Oleic Acid", "r": 2, "c": "Fatty acid", "a": ["oleic acid"], "s": "oleic-acid", "fa": true},
  {"n": "Olive Oil", "r": 2, "c": "Oil", "a": ["olea europaea fruit oil", "olive oil"], "s": "olive-oil", "fa": true},
  {"n": "Palmitic Acid", "r": 2, "c": "Fatty acid", "a": ["palmitic acid"], "s": "palmitic-acid", "fa": true},
  {"n": "Peanut Oil", "r": 2, "c": "Oil", "a": ["arachis hypogaea oil", "peanut oil"], "s": "peanut-oil", "fa": true},
  {"n": "Peppermint Oil", "r": 2, "c": "Essential oil", "a": ["mentha piperita oil", "peppermint oil"], "s": "peppermint-oil", "fa": false},
  {"n": "Retinyl Palmitate", "r": 2, "c": "Active", "a": ["retinyl palmitate"], "s": "retinyl-palmitate", "fa": true},
  {"n": "Steareth-2", "r": 2, "c": "Emulsifier", "a": ["steareth-2"], "s": "steareth-2", "fa": true},
  {"n": "Steareth-20", "r": 2, "c": "Emulsifier", "a": ["steareth-20"], "s": "steareth-20", "fa": true},
  {"n": "Stearic Acid", "r": 2, "c": "Fatty acid", "a": ["stearic acid"], "s": "stearic-acid", "fa": true},
  {"n": "Stearyl Alcohol", "r": 2, "c": "Fatty alcohol", "a": ["stearyl alcohol"], "s": "stearyl-alcohol", "fa": true},
  {"n": "Sweet Almond Oil", "r": 2, "c": "Oil", "a": ["almond oil", "prunus amygdalus dulcis oil", "sweet almond oil"], "s": "sweet-almond-oil", "fa": true},
  {"n": "Tamanu Oil", "r": 2, "c": "Oil", "a": ["calophyllum inophyllum seed oil", "tamanu oil"], "s": "tamanu-oil", "fa": true},
  {"n": "Tetrahexyldecyl Ascorbate", "r": 2, "c": "Active", "a": ["tetrahexyldecyl ascorbate"], "s": "tetrahexyldecyl-ascorbate", "fa": false},
  {"n": "Tocopherol", "r": 2, "c": "Active", "a": ["tocopherol", "tocopheryl acetate", "vitamin e"], "s": "tocopherol", "fa": true},
  {"n": "Wheat Bran Lipids", "r": 2, "c": "Oil", "a": ["wheat bran lipids"], "s": "wheat-bran-lipids", "fa": true},
  {"n": "Amodimethicone", "r": 1, "c": "Silicone", "a": ["amodimethicone"], "s": "amodimethicone", "fa": false},
  {"n": "Behenyl Alcohol", "r": 1, "c": "Fatty alcohol", "a": ["behenyl alcohol"], "s": "behenyl-alcohol", "fa": true},
  {"n": "Camellia / Tsubaki Oil", "r": 1, "c": "Oil", "a": ["camellia japonica seed oil", "camellia oil", "tsubaki oil"], "s": "camellia-tsubaki-oil", "fa": true},
  {"n": "Candelilla Wax", "r": 1, "c": "Wax", "a": ["candelilla wax", "euphorbia cerifera wax"], "s": "candelilla-wax", "fa": false},
  {"n": "Caprylic/Capric Triglyceride", "r": 1, "c": "Ester", "a": ["caprylic capric triglyceride", "caprylic/capric triglyceride"], "s": "caprylic-capric-triglyceride", "fa": false},
  {"n": "Carnauba Wax", "r": 1, "c": "Wax", "a": ["carnauba wax", "copernicia cerifera wax"], "s": "carnauba-wax", "fa": false},
  {"n": "Castor Oil", "r": 1, "c": "Oil", "a": ["castor oil", "ricinus communis seed oil"], "s": "castor-oil", "fa": true},
  {"n": "Cetearyl Ethylhexanoate", "r": 1, "c": "Ester", "a": ["cetearyl ethylhexanoate"], "s": "cetearyl-ethylhexanoate", "fa": true},
  {"n": "Cocamidopropyl Betaine", "r": 1, "c": "Surfactant", "a": ["cocamidopropyl betaine"], "s": "cocamidopropyl-betaine", "fa": false},
  {"n": "Coco-Caprylate", "r": 1, "c": "Ester", "a": ["coco caprylate", "coco-caprylate"], "s": "coco-caprylate", "fa": true},
  {"n": "Cupuacu Butter", "r": 1, "c": "Butter", "a": ["cupuacu butter", "theobroma grandiflorum seed butter"], "s": "cupuacu-butter", "fa": true},
  {"n": "Diisopropyl Adipate", "r": 1, "c": "Ester", "a": ["diisopropyl adipate"], "s": "diisopropyl-adipate", "fa": true},
  {"n": "Dimethicone", "r": 1, "c": "Silicone", "a": ["dimethicone"], "s": "dimethicone", "fa": false},
  {"n": "Dimethicone Crosspolymer", "r": 1, "c": "Silicone", "a": ["dimethicone crosspolymer"], "s": "dimethicone-crosspolymer", "fa": false},
  {"n": "Fragrance", "r": 1, "c": "Fragrance", "a": ["fragrance", "parfum"], "s": "fragrance", "fa": false},
  {"n": "Glyceryl Stearate", "r": 1, "c": "Ester", "a": ["glyceryl stearate"], "s": "glyceryl-stearate", "fa": true},
  {"n": "Grapeseed Oil", "r": 1, "c": "Oil", "a": ["grape seed oil", "grapeseed oil", "vitis vinifera seed oil"], "s": "grapeseed-oil", "fa": true},
  {"n": "Homosalate", "r": 1, "c": "Sunscreen", "a": ["homosalate"], "s": "homosalate", "fa": false},
  {"n": "Hydrogenated Castor Oil", "r": 1, "c": "Oil", "a": ["hydrogenated castor oil"], "s": "hydrogenated-castor-oil", "fa": true},
  {"n": "Hydrogenated Lecithin", "r": 1, "c": "Emulsifier", "a": ["hydrogenated lecithin"], "s": "hydrogenated-lecithin", "fa": true},
  {"n": "Isohexadecane", "r": 1, "c": "Ester", "a": ["isohexadecane"], "s": "isohexadecane", "fa": false},
  {"n": "Isononyl Isononanoate", "r": 1, "c": "Ester", "a": ["isononyl isononanoate"], "s": "isononyl-isononanoate", "fa": true},
  {"n": "Kokum Butter", "r": 1, "c": "Butter", "a": ["garcinia indica seed butter", "kokum butter"], "s": "kokum-butter", "fa": true},
  {"n": "Lavender Oil", "r": 1, "c": "Essential oil", "a": ["lavandula angustifolia oil", "lavender oil"], "s": "lavender-oil", "fa": false},
  {"n": "Limonene", "r": 1, "c": "Fragrance", "a": ["limonene"], "s": "limonene", "fa": false},
  {"n": "Linalool", "r": 1, "c": "Fragrance", "a": ["linalool"], "s": "linalool", "fa": false},
  {"n": "Marula Oil", "r": 1, "c": "Oil", "a": ["marula oil", "sclerocarya birrea seed oil"], "s": "marula-oil", "fa": true},
  {"n": "Meadowfoam Seed Oil", "r": 1, "c": "Oil", "a": ["limnanthes alba seed oil", "meadowfoam seed oil"], "s": "meadowfoam-seed-oil", "fa": true},
  {"n": "Mineral Oil", "r": 1, "c": "Oil", "a": ["mineral oil", "paraffinum liquidum"], "s": "mineral-oil", "fa": false},
  {"n": "Octinoxate", "r": 1, "c": "Sunscreen", "a": ["ethylhexyl methoxycinnamate", "octinoxate"], "s": "octinoxate", "fa": false},
  {"n": "Octocrylene", "r": 1, "c": "Sunscreen", "a": ["octocrylene"], "s": "octocrylene", "fa": false},
  {"n": "PEG-100 Stearate", "r": 1, "c": "Emulsifier", "a": ["peg-100 stearate"], "s": "peg-100-stearate", "fa": true},
  {"n": "PEG-150 Distearate", "r": 1, "c": "Emulsifier", "a": ["peg-150 distearate"], "s": "peg-150-distearate", "fa": true},
  {"n": "PEG-40 Stearate", "r": 1, "c": "Emulsifier", "a": ["peg-40 stearate"], "s": "peg-40-stearate", "fa": true},
  {"n": "Phenyl Trimethicone", "r": 1, "c": "Silicone", "a": ["phenyl trimethicone"], "s": "phenyl-trimethicone", "fa": false},
  {"n": "Polysorbate 80", "r": 1, "c": "Emulsifier", "a": ["polysorbate 80"], "s": "polysorbate-80", "fa": true},
  {"n": "Pomegranate Seed Oil", "r": 1, "c": "Oil", "a": ["pomegranate seed oil", "punica granatum seed oil"], "s": "pomegranate-seed-oil", "fa": true},
  {"n": "Retinol", "r": 1, "c": "Active", "a": ["retinol"], "s": "retinol", "fa": false},
  {"n": "Rosehip Oil", "r": 1, "c": "Oil", "a": ["rosa canina fruit oil", "rosehip oil", "rosehip seed oil"], "s": "rosehip-oil", "fa": true},
  {"n": "Sorbitan Stearate", "r": 1, "c": "Emulsifier", "a": ["sorbitan stearate"], "s": "sorbitan-stearate", "fa": true},
  {"n": "Squalane", "r": 1, "c": "Oil", "a": ["squalane"], "s": "squalane", "fa": false},
  {"n": "Squalene", "r": 1, "c": "Oil", "a": ["squalene"], "s": "squalene", "fa": false},
  {"n": "Talc", "r": 1, "c": "Mineral", "a": ["talc"], "s": "talc", "fa": false},
  {"n": "Tea Tree Oil", "r": 1, "c": "Essential oil", "a": ["melaleuca alternifolia leaf oil", "tea tree oil"], "s": "tea-tree-oil", "fa": false},
  {"n": "Titanium Dioxide", "r": 1, "c": "Sunscreen", "a": ["ci 77891", "titanium dioxide"], "s": "titanium-dioxide", "fa": false},
  {"n": "Zinc Oxide", "r": 1, "c": "Sunscreen", "a": ["zinc oxide"], "s": "zinc-oxide", "fa": false},
  {"n": "Acai Extract", "r": 0, "c": "Botanical extract", "a": ["acai extract"], "s": "acai-extract", "fa": false},
  {"n": "Acetyl Glucosamine", "r": 0, "c": "Functional", "a": ["acetyl glucosamine"], "s": "acetyl-glucosamine", "fa": false},
  {"n": "Acetyl Hexapeptide-8", "r": 0, "c": "Functional", "a": ["acetyl hexapeptide-8"], "s": "acetyl-hexapeptide-8", "fa": false},
  {"n": "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", "r": 0, "c": "Functional", "a": ["acrylates/c10-30 alkyl acrylate crosspolymer"], "s": "acrylates-c10-30-alkyl-acrylate-crosspolymer", "fa": false},
  {"n": "Adansonia Digitata Extract", "r": 0, "c": "Botanical extract", "a": ["adansonia digitata extract"], "s": "adansonia-digitata-extract", "fa": false},
  {"n": "Adapalene", "r": 0, "c": "Active", "a": ["adapalene"], "s": "adapalene", "fa": false},
  {"n": "Adenosine", "r": 0, "c": "Functional", "a": ["adenosine"], "s": "adenosine", "fa": false},
  {"n": "Agar", "r": 0, "c": "Functional", "a": ["agar"], "s": "agar", "fa": false},
  {"n": "Alcohol Denat.", "r": 0, "c": "Solvent", "a": ["alcohol denat", "alcohol denat.", "denatured alcohol"], "s": "alcohol-denat", "fa": false},
  {"n": "Allantoin", "r": 0, "c": "Soothing", "a": ["allantoin"], "s": "allantoin", "fa": false},
  {"n": "Allantoin Extract", "r": 0, "c": "Botanical extract", "a": ["allantoin extract"], "s": "allantoin-extract", "fa": false},
  {"n": "Allium Cepa Extract", "r": 0, "c": "Botanical extract", "a": ["allium cepa extract"], "s": "allium-cepa-extract", "fa": false},
  {"n": "Aloe Barbadensis Leaf Juice", "r": 0, "c": "Botanical extract", "a": ["aloe barbadensis leaf juice"], "s": "aloe-barbadensis-leaf-juice", "fa": false},
  {"n": "Aloe Extract", "r": 0, "c": "Botanical extract", "a": ["aloe extract"], "s": "aloe-extract", "fa": false},
  {"n": "Aloe Ferox Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["aloe ferox leaf extract"], "s": "aloe-ferox-leaf-extract", "fa": false},
  {"n": "Aloe Juice Powder", "r": 0, "c": "Botanical extract", "a": ["aloe juice powder"], "s": "aloe-juice-powder", "fa": false},
  {"n": "Aloe Powder", "r": 0, "c": "Botanical extract", "a": ["aloe powder"], "s": "aloe-powder", "fa": false},
  {"n": "Aloe Vera", "r": 0, "c": "Botanical extract", "a": ["aloe vera"], "s": "aloe-vera", "fa": false},
  {"n": "Alpha Lipoic Acid", "r": 0, "c": "Functional", "a": ["alpha lipoic acid"], "s": "alpha-lipoic-acid", "fa": false},
  {"n": "Alpha-Arbutin", "r": 0, "c": "Functional", "a": ["alpha-arbutin"], "s": "alpha-arbutin", "fa": false},
  {"n": "Aluminum Starch Octenylsuccinate", "r": 0, "c": "Functional", "a": ["aluminum starch octenylsuccinate"], "s": "aluminum-starch-octenylsuccinate", "fa": false},
  {"n": "Aminomethyl Propanol", "r": 0, "c": "Functional", "a": ["aminomethyl propanol"], "s": "aminomethyl-propanol", "fa": false},
  {"n": "Amla Extract", "r": 0, "c": "Botanical extract", "a": ["amla extract"], "s": "amla-extract", "fa": false},
  {"n": "Ammonium Lactate", "r": 0, "c": "Functional", "a": ["ammonium lactate"], "s": "ammonium-lactate", "fa": false},
  {"n": "Anisic Acid", "r": 0, "c": "Functional", "a": ["anisic acid"], "s": "anisic-acid", "fa": false},
  {"n": "Apple Extract", "r": 0, "c": "Botanical extract", "a": ["apple extract"], "s": "apple-extract", "fa": false},
  {"n": "Apricot Extract", "r": 0, "c": "Botanical extract", "a": ["apricot extract"], "s": "apricot-extract", "fa": false},
  {"n": "Arbutin", "r": 0, "c": "Functional", "a": ["arbutin"], "s": "arbutin", "fa": false},
  {"n": "Argan Oil", "r": 0, "c": "Oil", "a": ["argan oil", "argania spinosa kernel oil"], "s": "argan-oil", "fa": true},
  {"n": "Argireline", "r": 0, "c": "Functional", "a": ["argireline"], "s": "argireline", "fa": false},
  {"n": "Arnica Extract", "r": 0, "c": "Botanical extract", "a": ["arnica extract"], "s": "arnica-extract", "fa": false},
  {"n": "Arnica Montana Flower Extract", "r": 0, "c": "Botanical extract", "a": ["arnica montana flower extract"], "s": "arnica-montana-flower-extract", "fa": false},
  {"n": "Artemisia Vulgaris Extract", "r": 0, "c": "Botanical extract", "a": ["artemisia vulgaris extract"], "s": "artemisia-vulgaris-extract", "fa": false},
  {"n": "Artichoke Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["artichoke leaf extract"], "s": "artichoke-leaf-extract", "fa": false},
  {"n": "Ascorbic Acid", "r": 0, "c": "Active", "a": ["ascorbic acid", "vitamin c"], "s": "ascorbic-acid", "fa": false},
  {"n": "Ascorbyl Glucoside", "r": 0, "c": "Functional", "a": ["ascorbyl glucoside"], "s": "ascorbyl-glucoside", "fa": false},
  {"n": "Ascorbyl Palmitate", "r": 0, "c": "Functional", "a": ["ascorbyl palmitate"], "s": "ascorbyl-palmitate", "fa": true},
  {"n": "Ashwagandha Extract", "r": 0, "c": "Botanical extract", "a": ["ashwagandha extract"], "s": "ashwagandha-extract", "fa": false},
  {"n": "Asiaticoside", "r": 0, "c": "Botanical extract", "a": ["asiaticoside"], "s": "asiaticoside", "fa": false},
  {"n": "Asparagus Extract", "r": 0, "c": "Botanical extract", "a": ["asparagus extract"], "s": "asparagus-extract", "fa": false},
  {"n": "Avena Sativa Kernel Extract", "r": 0, "c": "Botanical extract", "a": ["avena sativa kernel extract"], "s": "avena-sativa-kernel-extract", "fa": false},
  {"n": "Avobenzone", "r": 0, "c": "Sunscreen", "a": ["avobenzone", "butyl methoxydibenzoylmethane"], "s": "avobenzone", "fa": false},
  {"n": "Azadirachta Indica Extract", "r": 0, "c": "Botanical extract", "a": ["azadirachta indica extract"], "s": "azadirachta-indica-extract", "fa": false},
  {"n": "Azelaic Acid", "r": 0, "c": "Active", "a": ["azelaic acid"], "s": "azelaic-acid", "fa": false},
  {"n": "BHA Preservative", "r": 0, "c": "Functional", "a": ["bha preservative"], "s": "bha-preservative", "fa": false},
  {"n": "BHT", "r": 0, "c": "Functional", "a": ["bht"], "s": "bht", "fa": false},
  {"n": "Bakuchiol", "r": 0, "c": "Active", "a": ["bakuchiol"], "s": "bakuchiol", "fa": false},
  {"n": "Bamboo Extract", "r": 0, "c": "Botanical extract", "a": ["bamboo extract"], "s": "bamboo-extract", "fa": false},
  {"n": "Bambusa Vulgaris Extract", "r": 0, "c": "Botanical extract", "a": ["bambusa vulgaris extract"], "s": "bambusa-vulgaris-extract", "fa": false},
  {"n": "Banana Extract", "r": 0, "c": "Botanical extract", "a": ["banana extract"], "s": "banana-extract", "fa": false},
  {"n": "Baobab Extract", "r": 0, "c": "Botanical extract", "a": ["baobab extract"], "s": "baobab-extract", "fa": false},
  {"n": "Barley Extract", "r": 0, "c": "Botanical extract", "a": ["barley extract"], "s": "barley-extract", "fa": false},
  {"n": "Basil Extract", "r": 0, "c": "Botanical extract", "a": ["basil extract"], "s": "basil-extract", "fa": false},
  {"n": "Beetroot Extract", "r": 0, "c": "Botanical extract", "a": ["beetroot extract"], "s": "beetroot-extract", "fa": false},
  {"n": "Bentonite", "r": 0, "c": "Clay", "a": ["bentonite"], "s": "bentonite", "fa": false},
  {"n": "Benzoyl Peroxide", "r": 0, "c": "Active", "a": ["benzoyl peroxide"], "s": "benzoyl-peroxide", "fa": false},
  {"n": "Benzyl Alcohol", "r": 0, "c": "Functional", "a": ["benzyl alcohol"], "s": "benzyl-alcohol", "fa": false},
  {"n": "Bergamot Extract", "r": 0, "c": "Botanical extract", "a": ["bergamot extract"], "s": "bergamot-extract", "fa": false},
  {"n": "Beta-Glucan", "r": 0, "c": "Botanical extract", "a": ["beta-glucan"], "s": "beta-glucan", "fa": false},
  {"n": "Betaine", "r": 0, "c": "Humectant", "a": ["betaine"], "s": "betaine", "fa": false},
  {"n": "Bifida Ferment Lysate", "r": 0, "c": "Botanical extract", "a": ["bifida ferment lysate"], "s": "bifida-ferment-lysate", "fa": true},
  {"n": "Bilberry Extract", "r": 0, "c": "Botanical extract", "a": ["bilberry extract"], "s": "bilberry-extract", "fa": false},
  {"n": "Biotin", "r": 0, "c": "Functional", "a": ["biotin"], "s": "biotin", "fa": false},
  {"n": "Birch Extract", "r": 0, "c": "Botanical extract", "a": ["birch extract"], "s": "birch-extract", "fa": false},
  {"n": "Black Tea Extract", "r": 0, "c": "Botanical extract", "a": ["black tea extract"], "s": "black-tea-extract", "fa": false},
  {"n": "Blackberry Extract", "r": 0, "c": "Botanical extract", "a": ["blackberry extract"], "s": "blackberry-extract", "fa": false},
  {"n": "Blueberry Extract", "r": 0, "c": "Botanical extract", "a": ["blueberry extract"], "s": "blueberry-extract", "fa": false},
  {"n": "Boron Nitride", "r": 0, "c": "Functional", "a": ["boron nitride"], "s": "boron-nitride", "fa": false},
  {"n": "Boswellia Serrata Extract", "r": 0, "c": "Botanical extract", "a": ["boswellia serrata extract"], "s": "boswellia-serrata-extract", "fa": false},
  {"n": "Brahmi Extract", "r": 0, "c": "Botanical extract", "a": ["brahmi extract"], "s": "brahmi-extract", "fa": false},
  {"n": "Broccoli Extract", "r": 0, "c": "Botanical extract", "a": ["broccoli extract"], "s": "broccoli-extract", "fa": false},
  {"n": "Burdock Root Extract", "r": 0, "c": "Botanical extract", "a": ["burdock root extract"], "s": "burdock-root-extract", "fa": false},
  {"n": "Butylene Glycol", "r": 0, "c": "Humectant", "a": ["butylene glycol"], "s": "butylene-glycol", "fa": false},
  {"n": "Cabbage Extract", "r": 0, "c": "Botanical extract", "a": ["cabbage extract"], "s": "cabbage-extract", "fa": false},
  {"n": "Cactus Extract", "r": 0, "c": "Botanical extract", "a": ["cactus extract"], "s": "cactus-extract", "fa": false},
  {"n": "Caffeine", "r": 0, "c": "Botanical extract", "a": ["caffeine"], "s": "caffeine", "fa": false},
  {"n": "Calcium Carbonate", "r": 0, "c": "Functional", "a": ["calcium carbonate"], "s": "calcium-carbonate", "fa": false},
  {"n": "Calcium Chloride", "r": 0, "c": "Functional", "a": ["calcium chloride"], "s": "calcium-chloride", "fa": false},
  {"n": "Calcium Pantothenate", "r": 0, "c": "Functional", "a": ["calcium pantothenate"], "s": "calcium-pantothenate", "fa": false},
  {"n": "Calendula Extract", "r": 0, "c": "Botanical extract", "a": ["calendula extract"], "s": "calendula-extract", "fa": false},
  {"n": "Calendula Officinalis Flower Extract", "r": 0, "c": "Botanical extract", "a": ["calendula officinalis flower extract"], "s": "calendula-officinalis-flower-extract", "fa": false},
  {"n": "Camellia Japonica Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["camellia japonica leaf extract"], "s": "camellia-japonica-leaf-extract", "fa": false},
  {"n": "Camellia Sinensis Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["camellia sinensis leaf extract"], "s": "camellia-sinensis-leaf-extract", "fa": false},
  {"n": "Caprylhydroxamic Acid", "r": 0, "c": "Functional", "a": ["caprylhydroxamic acid"], "s": "caprylhydroxamic-acid", "fa": false},
  {"n": "Caprylyl Glycol", "r": 0, "c": "Functional", "a": ["caprylyl glycol"], "s": "caprylyl-glycol", "fa": false},
  {"n": "Carbomer", "r": 0, "c": "Thickener", "a": ["carbomer"], "s": "carbomer", "fa": false},
  {"n": "Cardamom Extract", "r": 0, "c": "Botanical extract", "a": ["cardamom extract"], "s": "cardamom-extract", "fa": false},
  {"n": "Carica Papaya Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["carica papaya fruit extract"], "s": "carica-papaya-fruit-extract", "fa": false},
  {"n": "Carnosine", "r": 0, "c": "Functional", "a": ["carnosine"], "s": "carnosine", "fa": false},
  {"n": "Carrot Extract", "r": 0, "c": "Botanical extract", "a": ["carrot extract"], "s": "carrot-extract", "fa": false},
  {"n": "Cedarwood Extract", "r": 0, "c": "Botanical extract", "a": ["cedarwood extract"], "s": "cedarwood-extract", "fa": false},
  {"n": "Celery Extract", "r": 0, "c": "Botanical extract", "a": ["celery extract"], "s": "celery-extract", "fa": false},
  {"n": "Cellulose Gum", "r": 0, "c": "Functional", "a": ["cellulose gum"], "s": "cellulose-gum", "fa": false},
  {"n": "Centaurea Cyanus Flower Water", "r": 0, "c": "Botanical extract", "a": ["centaurea cyanus flower water"], "s": "centaurea-cyanus-flower-water", "fa": false},
  {"n": "Centella Asiatica Extract", "r": 0, "c": "Botanical extract", "a": ["centella asiatica extract"], "s": "centella-asiatica-extract", "fa": false},
  {"n": "Cetearyl Glucoside", "r": 0, "c": "Emulsifier", "a": ["cetearyl glucoside"], "s": "cetearyl-glucoside", "fa": false},
  {"n": "Cha de Bugre Extract", "r": 0, "c": "Botanical extract", "a": ["cha de bugre extract"], "s": "cha-de-bugre-extract", "fa": false},
  {"n": "Chamomile Extract", "r": 0, "c": "Botanical extract", "a": ["chamomile extract"], "s": "chamomile-extract", "fa": false},
  {"n": "Chamomilla Recutita Flower Extract", "r": 0, "c": "Botanical extract", "a": ["chamomilla recutita flower extract"], "s": "chamomilla-recutita-flower-extract", "fa": false},
  {"n": "Charcoal", "r": 0, "c": "Misc", "a": ["activated charcoal", "charcoal"], "s": "charcoal", "fa": false},
  {"n": "Chickweed Extract", "r": 0, "c": "Botanical extract", "a": ["chickweed extract"], "s": "chickweed-extract", "fa": false},
  {"n": "Chlorella Extract", "r": 0, "c": "Botanical extract", "a": ["chlorella extract"], "s": "chlorella-extract", "fa": false},
  {"n": "Chlorphenesin", "r": 0, "c": "Functional", "a": ["chlorphenesin"], "s": "chlorphenesin", "fa": false},
  {"n": "Cica", "r": 0, "c": "Botanical extract", "a": ["cica"], "s": "cica", "fa": false},
  {"n": "Cilantro Extract", "r": 0, "c": "Botanical extract", "a": ["cilantro extract"], "s": "cilantro-extract", "fa": false},
  {"n": "Cinnamon Extract", "r": 0, "c": "Botanical extract", "a": ["cinnamon extract"], "s": "cinnamon-extract", "fa": false},
  {"n": "Citric Acid", "r": 0, "c": "Functional", "a": ["citric acid"], "s": "citric-acid", "fa": false},
  {"n": "Citrus Limon Peel Extract", "r": 0, "c": "Botanical extract", "a": ["citrus limon peel extract"], "s": "citrus-limon-peel-extract", "fa": false},
  {"n": "Cleavers Extract", "r": 0, "c": "Botanical extract", "a": ["cleavers extract"], "s": "cleavers-extract", "fa": false},
  {"n": "Clove Extract", "r": 0, "c": "Botanical extract", "a": ["clove extract"], "s": "clove-extract", "fa": false},
  {"n": "Coco-Glucoside", "r": 0, "c": "Surfactant", "a": ["coco glucoside", "coco-glucoside"], "s": "coco-glucoside", "fa": false},
  {"n": "Cocoa Extract", "r": 0, "c": "Botanical extract", "a": ["cocoa extract"], "s": "cocoa-extract", "fa": false},
  {"n": "Coenzyme Q10", "r": 0, "c": "Functional", "a": ["coenzyme q10"], "s": "coenzyme-q10", "fa": false},
  {"n": "Coffea Arabica Seed Extract", "r": 0, "c": "Botanical extract", "a": ["coffea arabica seed extract"], "s": "coffea-arabica-seed-extract", "fa": false},
  {"n": "Coffee Extract", "r": 0, "c": "Botanical extract", "a": ["coffee extract"], "s": "coffee-extract", "fa": false},
  {"n": "Collagen", "r": 0, "c": "Botanical extract", "a": ["collagen"], "s": "collagen", "fa": false},
  {"n": "Colloidal Oatmeal", "r": 0, "c": "Soothing", "a": ["colloidal oatmeal"], "s": "colloidal-oatmeal", "fa": false},
  {"n": "Comfrey Extract", "r": 0, "c": "Botanical extract", "a": ["comfrey extract"], "s": "comfrey-extract", "fa": false},
  {"n": "Copper PCA", "r": 0, "c": "Functional", "a": ["copper pca"], "s": "copper-pca", "fa": false},
  {"n": "Copper Tripeptide-1", "r": 0, "c": "Functional", "a": ["copper tripeptide-1"], "s": "copper-tripeptide-1", "fa": false},
  {"n": "Corn Starch", "r": 0, "c": "Functional", "a": ["corn starch"], "s": "corn-starch", "fa": false},
  {"n": "Cornflower Extract", "r": 0, "c": "Botanical extract", "a": ["cornflower extract"], "s": "cornflower-extract", "fa": false},
  {"n": "Cranberry Extract", "r": 0, "c": "Botanical extract", "a": ["cranberry extract"], "s": "cranberry-extract", "fa": false},
  {"n": "Cucumber Extract", "r": 0, "c": "Botanical extract", "a": ["cucumber extract"], "s": "cucumber-extract", "fa": false},
  {"n": "Cucumis Sativus Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["cucumis sativus fruit extract"], "s": "cucumis-sativus-fruit-extract", "fa": false},
  {"n": "Cucurbita Pepo Seed Extract", "r": 0, "c": "Botanical extract", "a": ["cucurbita pepo seed extract"], "s": "cucurbita-pepo-seed-extract", "fa": false},
  {"n": "Curcuma Longa Root Extract", "r": 0, "c": "Botanical extract", "a": ["curcuma longa root extract"], "s": "curcuma-longa-root-extract", "fa": false},
  {"n": "Cyanocobalamin", "r": 0, "c": "Functional", "a": ["cyanocobalamin"], "s": "cyanocobalamin", "fa": false},
  {"n": "Cyclodextrin", "r": 0, "c": "Functional", "a": ["cyclodextrin"], "s": "cyclodextrin", "fa": false},
  {"n": "Cyclohexasiloxane", "r": 0, "c": "Silicone", "a": ["cyclohexasiloxane"], "s": "cyclohexasiloxane", "fa": false},
  {"n": "Cyclomethicone", "r": 0, "c": "Silicone", "a": ["cyclomethicone"], "s": "cyclomethicone", "fa": false},
  {"n": "Cyclopentasiloxane", "r": 0, "c": "Silicone", "a": ["cyclopentasiloxane"], "s": "cyclopentasiloxane", "fa": false},
  {"n": "Daisy Extract", "r": 0, "c": "Botanical extract", "a": ["daisy extract"], "s": "daisy-extract", "fa": false},
  {"n": "Dandelion Extract", "r": 0, "c": "Botanical extract", "a": ["dandelion extract"], "s": "dandelion-extract", "fa": false},
  {"n": "Date Extract", "r": 0, "c": "Botanical extract", "a": ["date extract"], "s": "date-extract", "fa": false},
  {"n": "Daucus Carota Sativa Root Extract", "r": 0, "c": "Botanical extract", "a": ["daucus carota sativa root extract"], "s": "daucus-carota-sativa-root-extract", "fa": false},
  {"n": "Decyl Glucoside", "r": 0, "c": "Surfactant", "a": ["decyl glucoside"], "s": "decyl-glucoside", "fa": false},
  {"n": "Dehydroacetic Acid", "r": 0, "c": "Functional", "a": ["dehydroacetic acid"], "s": "dehydroacetic-acid", "fa": false},
  {"n": "Dill Extract", "r": 0, "c": "Botanical extract", "a": ["dill extract"], "s": "dill-extract", "fa": false},
  {"n": "Dipropylene Glycol", "r": 0, "c": "Functional", "a": ["dipropylene glycol"], "s": "dipropylene-glycol", "fa": false},
  {"n": "Disodium Cocoamphodiacetate", "r": 0, "c": "Functional", "a": ["disodium cocoamphodiacetate"], "s": "disodium-cocoamphodiacetate", "fa": false},
  {"n": "Disodium EDTA", "r": 0, "c": "Functional", "a": ["disodium edta"], "s": "disodium-edta", "fa": false},
  {"n": "Echinacea Extract", "r": 0, "c": "Botanical extract", "a": ["echinacea extract"], "s": "echinacea-extract", "fa": false},
  {"n": "Ectoin", "r": 0, "c": "Botanical extract", "a": ["ectoin"], "s": "ectoin", "fa": false},
  {"n": "Edelweiss Extract", "r": 0, "c": "Botanical extract", "a": ["edelweiss extract"], "s": "edelweiss-extract", "fa": false},
  {"n": "Elastin", "r": 0, "c": "Botanical extract", "a": ["elastin"], "s": "elastin", "fa": false},
  {"n": "Elderflower Extract", "r": 0, "c": "Botanical extract", "a": ["elderflower extract"], "s": "elderflower-extract", "fa": false},
  {"n": "Equisetum Arvense Extract", "r": 0, "c": "Botanical extract", "a": ["equisetum arvense extract"], "s": "equisetum-arvense-extract", "fa": false},
  {"n": "Ergothioneine", "r": 0, "c": "Functional", "a": ["ergothioneine"], "s": "ergothioneine", "fa": false},
  {"n": "Ethanol", "r": 0, "c": "Functional", "a": ["ethanol"], "s": "ethanol", "fa": false},
  {"n": "Ethylhexylglycerin", "r": 0, "c": "Functional", "a": ["ethylhexylglycerin"], "s": "ethylhexylglycerin", "fa": false},
  {"n": "Eucalyptus Extract", "r": 0, "c": "Botanical extract", "a": ["eucalyptus extract"], "s": "eucalyptus-extract", "fa": false},
  {"n": "Fennel Extract", "r": 0, "c": "Botanical extract", "a": ["fennel extract"], "s": "fennel-extract", "fa": false},
  {"n": "Fermented Rice Water", "r": 0, "c": "Botanical extract", "a": ["fermented rice water"], "s": "fermented-rice-water", "fa": true},
  {"n": "Ferulate", "r": 0, "c": "Functional", "a": ["ferulate"], "s": "ferulate", "fa": false},
  {"n": "Ferulic Acid", "r": 0, "c": "Botanical extract", "a": ["ferulic acid"], "s": "ferulic-acid", "fa": false},
  {"n": "Fig Extract", "r": 0, "c": "Botanical extract", "a": ["fig extract"], "s": "fig-extract", "fa": false},
  {"n": "Folic Acid", "r": 0, "c": "Functional", "a": ["folic acid"], "s": "folic-acid", "fa": false},
  {"n": "Frankincense Extract", "r": 0, "c": "Botanical extract", "a": ["frankincense extract"], "s": "frankincense-extract", "fa": false},
  {"n": "Fructose", "r": 0, "c": "Functional", "a": ["fructose"], "s": "fructose", "fa": false},
  {"n": "Galactomyces Ferment Filtrate", "r": 0, "c": "Botanical extract", "a": ["galactomyces ferment filtrate"], "s": "galactomyces-ferment-filtrate", "fa": true},
  {"n": "Garlic Extract", "r": 0, "c": "Botanical extract", "a": ["garlic extract"], "s": "garlic-extract", "fa": false},
  {"n": "Gellan Gum", "r": 0, "c": "Functional", "a": ["gellan gum"], "s": "gellan-gum", "fa": false},
  {"n": "Ginger Root Extract", "r": 0, "c": "Botanical extract", "a": ["ginger root extract"], "s": "ginger-root-extract", "fa": false},
  {"n": "Ginkgo Biloba Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["ginkgo biloba leaf extract"], "s": "ginkgo-biloba-leaf-extract", "fa": false},
  {"n": "Ginseng Extract", "r": 0, "c": "Botanical extract", "a": ["ginseng extract"], "s": "ginseng-extract", "fa": false},
  {"n": "Gluconolactone", "r": 0, "c": "Functional", "a": ["gluconolactone"], "s": "gluconolactone", "fa": false},
  {"n": "Glucose", "r": 0, "c": "Functional", "a": ["glucose"], "s": "glucose", "fa": false},
  {"n": "Glutathione", "r": 0, "c": "Functional", "a": ["glutathione"], "s": "glutathione", "fa": false},
  {"n": "Glycereth-26", "r": 0, "c": "Humectant", "a": ["glycereth-26"], "s": "glycereth-26", "fa": false},
  {"n": "Glycerin", "r": 0, "c": "Humectant", "a": ["glycerin", "glycerine", "glycerol"], "s": "glycerin", "fa": false},
  {"n": "Glyceryl Caprylate", "r": 0, "c": "Functional", "a": ["glyceryl caprylate"], "s": "glyceryl-caprylate", "fa": false},
  {"n": "Glyceryl Undecylenate", "r": 0, "c": "Functional", "a": ["glyceryl undecylenate"], "s": "glyceryl-undecylenate", "fa": false},
  {"n": "Glycine Soja Seed Extract", "r": 0, "c": "Botanical extract", "a": ["glycine soja seed extract"], "s": "glycine-soja-seed-extract", "fa": false},
  {"n": "Glycolic Acid", "r": 0, "c": "Active", "a": ["glycolic acid"], "s": "glycolic-acid", "fa": false},
  {"n": "Glycyrrhiza Glabra Root Extract", "r": 0, "c": "Botanical extract", "a": ["glycyrrhiza glabra root extract"], "s": "glycyrrhiza-glabra-root-extract", "fa": false},
  {"n": "Goji Berry Extract", "r": 0, "c": "Botanical extract", "a": ["goji berry extract"], "s": "goji-berry-extract", "fa": false},
  {"n": "Gotu Kola Extract", "r": 0, "c": "Botanical extract", "a": ["gotu kola extract"], "s": "gotu-kola-extract", "fa": false},
  {"n": "Grape Extract", "r": 0, "c": "Botanical extract", "a": ["grape extract"], "s": "grape-extract", "fa": false},
  {"n": "Grapefruit Extract", "r": 0, "c": "Botanical extract", "a": ["grapefruit extract"], "s": "grapefruit-extract", "fa": false},
  {"n": "Green Tea Extract", "r": 0, "c": "Botanical extract", "a": ["green tea extract"], "s": "green-tea-extract", "fa": false},
  {"n": "Guar Hydroxypropyltrimonium Chloride", "r": 0, "c": "Functional", "a": ["guar hydroxypropyltrimonium chloride"], "s": "guar-hydroxypropyltrimonium-chloride", "fa": false},
  {"n": "Guarana Extract", "r": 0, "c": "Botanical extract", "a": ["guarana extract"], "s": "guarana-extract", "fa": false},
  {"n": "HDI/Trimethylol Hexyllactone Crosspolymer", "r": 0, "c": "Functional", "a": ["hdi/trimethylol hexyllactone crosspolymer"], "s": "hdi-trimethylol-hexyllactone-crosspolymer", "fa": false},
  {"n": "Hamamelis Virginiana Water", "r": 0, "c": "Botanical extract", "a": ["hamamelis virginiana water"], "s": "hamamelis-virginiana-water", "fa": false},
  {"n": "Hawthorn Extract", "r": 0, "c": "Botanical extract", "a": ["hawthorn extract"], "s": "hawthorn-extract", "fa": false},
  {"n": "Heartleaf Extract", "r": 0, "c": "Botanical extract", "a": ["heartleaf extract"], "s": "heartleaf-extract", "fa": false},
  {"n": "Helichrysum Extract", "r": 0, "c": "Botanical extract", "a": ["helichrysum extract"], "s": "helichrysum-extract", "fa": false},
  {"n": "Hemp Seed Oil", "r": 0, "c": "Oil", "a": ["cannabis sativa seed oil", "hemp seed oil"], "s": "hemp-seed-oil", "fa": true},
  {"n": "Hexapeptide-9", "r": 0, "c": "Functional", "a": ["hexapeptide-9"], "s": "hexapeptide-9", "fa": false},
  {"n": "Hexylene Glycol", "r": 0, "c": "Functional", "a": ["hexylene glycol"], "s": "hexylene-glycol", "fa": false},
  {"n": "Hibiscus Extract", "r": 0, "c": "Botanical extract", "a": ["hibiscus extract"], "s": "hibiscus-extract", "fa": false},
  {"n": "Hippophae Rhamnoides Extract", "r": 0, "c": "Botanical extract", "a": ["hippophae rhamnoides extract"], "s": "hippophae-rhamnoides-extract", "fa": false},
  {"n": "Holy Basil Extract", "r": 0, "c": "Botanical extract", "a": ["holy basil extract"], "s": "holy-basil-extract", "fa": false},
  {"n": "Honey Extract", "r": 0, "c": "Botanical extract", "a": ["honey extract"], "s": "honey-extract", "fa": false},
  {"n": "Hops Extract", "r": 0, "c": "Botanical extract", "a": ["hops extract"], "s": "hops-extract", "fa": false},
  {"n": "Horsetail Extract", "r": 0, "c": "Botanical extract", "a": ["horsetail extract"], "s": "horsetail-extract", "fa": false},
  {"n": "Houttuynia Cordata Extract", "r": 0, "c": "Botanical extract", "a": ["houttuynia cordata extract"], "s": "houttuynia-cordata-extract", "fa": false},
  {"n": "Hyaluronic Acid", "r": 0, "c": "Humectant", "a": ["hyaluronic acid", "sodium hyaluronate"], "s": "hyaluronic-acid", "fa": false},
  {"n": "Hydrated Silica", "r": 0, "c": "Functional", "a": ["hydrated silica"], "s": "hydrated-silica", "fa": false},
  {"n": "Hydrolyzed Collagen", "r": 0, "c": "Botanical extract", "a": ["hydrolyzed collagen"], "s": "hydrolyzed-collagen", "fa": false},
  {"n": "Hydrolyzed Hyaluronic Acid", "r": 0, "c": "Functional", "a": ["hydrolyzed hyaluronic acid"], "s": "hydrolyzed-hyaluronic-acid", "fa": false},
  {"n": "Hydrolyzed Silk", "r": 0, "c": "Botanical extract", "a": ["hydrolyzed silk"], "s": "hydrolyzed-silk", "fa": false},
  {"n": "Hydrolyzed Wheat Protein", "r": 0, "c": "Botanical extract", "a": ["hydrolyzed wheat protein"], "s": "hydrolyzed-wheat-protein", "fa": false},
  {"n": "Hydroxyethylcellulose", "r": 0, "c": "Thickener", "a": ["hydroxyethylcellulose"], "s": "hydroxyethylcellulose", "fa": false},
  {"n": "Hydroxypropyl Cyclodextrin", "r": 0, "c": "Functional", "a": ["hydroxypropyl cyclodextrin"], "s": "hydroxypropyl-cyclodextrin", "fa": false},
  {"n": "Hydroxypropyl Guar", "r": 0, "c": "Functional", "a": ["hydroxypropyl guar"], "s": "hydroxypropyl-guar", "fa": false},
  {"n": "Idebenone", "r": 0, "c": "Functional", "a": ["idebenone"], "s": "idebenone", "fa": false},
  {"n": "Inositol", "r": 0, "c": "Functional", "a": ["inositol"], "s": "inositol", "fa": false},
  {"n": "Inulin", "r": 0, "c": "Functional", "a": ["inulin"], "s": "inulin", "fa": false},
  {"n": "Iron Oxides", "r": 0, "c": "Colorant", "a": ["ci 77491", "ci 77492", "ci 77499", "iron oxides"], "s": "iron-oxides", "fa": false},
  {"n": "Isopentyldiol", "r": 0, "c": "Functional", "a": ["isopentyldiol"], "s": "isopentyldiol", "fa": false},
  {"n": "Isopropyl Alcohol", "r": 0, "c": "Functional", "a": ["isopropyl alcohol"], "s": "isopropyl-alcohol", "fa": false},
  {"n": "Jasmine Extract", "r": 0, "c": "Botanical extract", "a": ["jasmine extract"], "s": "jasmine-extract", "fa": false},
  {"n": "Kale Extract", "r": 0, "c": "Botanical extract", "a": ["kale extract"], "s": "kale-extract", "fa": false},
  {"n": "Kaolin", "r": 0, "c": "Clay", "a": ["kaolin"], "s": "kaolin", "fa": false},
  {"n": "Keratin", "r": 0, "c": "Botanical extract", "a": ["keratin"], "s": "keratin", "fa": false},
  {"n": "Kojic Acid", "r": 0, "c": "Functional", "a": ["kojic acid"], "s": "kojic-acid", "fa": false},
  {"n": "Lactic Acid", "r": 0, "c": "Active", "a": ["lactic acid"], "s": "lactic-acid", "fa": false},
  {"n": "Lactic Acid Bacteria", "r": 0, "c": "Functional", "a": ["lactic acid bacteria"], "s": "lactic-acid-bacteria", "fa": false},
  {"n": "Lactobacillus Ferment", "r": 0, "c": "Botanical extract", "a": ["lactobacillus ferment"], "s": "lactobacillus-ferment", "fa": true},
  {"n": "Lactobionic Acid", "r": 0, "c": "Functional", "a": ["lactobionic acid"], "s": "lactobionic-acid", "fa": false},
  {"n": "Lauryl Glucoside", "r": 0, "c": "Functional", "a": ["lauryl glucoside"], "s": "lauryl-glucoside", "fa": false},
  {"n": "Lavandula Angustifolia Flower Extract", "r": 0, "c": "Botanical extract", "a": ["lavandula angustifolia flower extract"], "s": "lavandula-angustifolia-flower-extract", "fa": false},
  {"n": "Lavender Extract", "r": 0, "c": "Botanical extract", "a": ["lavender extract"], "s": "lavender-extract", "fa": false},
  {"n": "Lemon Balm Extract", "r": 0, "c": "Botanical extract", "a": ["lemon balm extract"], "s": "lemon-balm-extract", "fa": false},
  {"n": "Lemon Peel Extract", "r": 0, "c": "Botanical extract", "a": ["lemon peel extract"], "s": "lemon-peel-extract", "fa": false},
  {"n": "Leontopodium Alpinum Extract", "r": 0, "c": "Botanical extract", "a": ["leontopodium alpinum extract"], "s": "leontopodium-alpinum-extract", "fa": false},
  {"n": "Lettuce Extract", "r": 0, "c": "Botanical extract", "a": ["lettuce extract"], "s": "lettuce-extract", "fa": false},
  {"n": "Levulinic Acid", "r": 0, "c": "Functional", "a": ["levulinic acid"], "s": "levulinic-acid", "fa": false},
  {"n": "Licorice Root Extract", "r": 0, "c": "Botanical extract", "a": ["licorice root extract"], "s": "licorice-root-extract", "fa": false},
  {"n": "Linden Extract", "r": 0, "c": "Botanical extract", "a": ["linden extract"], "s": "linden-extract", "fa": false},
  {"n": "Linoleic Acid", "r": 0, "c": "Fatty acid", "a": ["linoleic acid"], "s": "linoleic-acid", "fa": true},
  {"n": "Lotus Extract", "r": 0, "c": "Botanical extract", "a": ["lotus extract"], "s": "lotus-extract", "fa": false},
  {"n": "Madecassoside", "r": 0, "c": "Botanical extract", "a": ["madecassoside"], "s": "madecassoside", "fa": false},
  {"n": "Magnesium Ascorbyl Phosphate", "r": 0, "c": "Active", "a": ["magnesium ascorbyl phosphate"], "s": "magnesium-ascorbyl-phosphate", "fa": false},
  {"n": "Magnesium Chloride", "r": 0, "c": "Functional", "a": ["magnesium chloride"], "s": "magnesium-chloride", "fa": false},
  {"n": "Magnesium Stearate", "r": 0, "c": "Functional", "a": ["magnesium stearate"], "s": "magnesium-stearate", "fa": true},
  {"n": "Magnesium Sulfate", "r": 0, "c": "Functional", "a": ["magnesium sulfate"], "s": "magnesium-sulfate", "fa": false},
  {"n": "Malic Acid", "r": 0, "c": "Functional", "a": ["malic acid"], "s": "malic-acid", "fa": false},
  {"n": "Mallow Extract", "r": 0, "c": "Botanical extract", "a": ["mallow extract"], "s": "mallow-extract", "fa": false},
  {"n": "Maltodextrin", "r": 0, "c": "Functional", "a": ["maltodextrin"], "s": "maltodextrin", "fa": false},
  {"n": "Mandarin Orange Extract", "r": 0, "c": "Botanical extract", "a": ["mandarin orange extract"], "s": "mandarin-orange-extract", "fa": false},
  {"n": "Mandelic Acid", "r": 0, "c": "Active", "a": ["mandelic acid"], "s": "mandelic-acid", "fa": false},
  {"n": "Manganese PCA", "r": 0, "c": "Functional", "a": ["manganese pca"], "s": "manganese-pca", "fa": false},
  {"n": "Mango Butter", "r": 0, "c": "Butter", "a": ["mangifera indica seed butter", "mango butter"], "s": "mango-butter", "fa": true},
  {"n": "Mango Extract", "r": 0, "c": "Botanical extract", "a": ["mango extract"], "s": "mango-extract", "fa": false},
  {"n": "Manuka Honey", "r": 0, "c": "Botanical extract", "a": ["manuka honey"], "s": "manuka-honey", "fa": false},
  {"n": "Marigold Extract", "r": 0, "c": "Botanical extract", "a": ["marigold extract"], "s": "marigold-extract", "fa": false},
  {"n": "Maritime Pine Extract", "r": 0, "c": "Botanical extract", "a": ["maritime pine extract"], "s": "maritime-pine-extract", "fa": false},
  {"n": "Marshmallow Root Extract", "r": 0, "c": "Botanical extract", "a": ["marshmallow root extract"], "s": "marshmallow-root-extract", "fa": false},
  {"n": "Matcha Extract", "r": 0, "c": "Botanical extract", "a": ["matcha extract"], "s": "matcha-extract", "fa": false},
  {"n": "Mate Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["mate leaf extract"], "s": "mate-leaf-extract", "fa": false},
  {"n": "Matrixyl", "r": 0, "c": "Functional", "a": ["matrixyl"], "s": "matrixyl", "fa": false},
  {"n": "Melissa Officinalis Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["melissa officinalis leaf extract"], "s": "melissa-officinalis-leaf-extract", "fa": false},
  {"n": "Methylparaben", "r": 0, "c": "Functional", "a": ["methylparaben"], "s": "methylparaben", "fa": false},
  {"n": "Methylpropanediol", "r": 0, "c": "Functional", "a": ["methylpropanediol"], "s": "methylpropanediol", "fa": false},
  {"n": "Mica", "r": 0, "c": "Colorant", "a": ["ci 77019", "mica"], "s": "mica", "fa": false},
  {"n": "Moringa Extract", "r": 0, "c": "Botanical extract", "a": ["moringa extract"], "s": "moringa-extract", "fa": false},
  {"n": "Mugwort Extract", "r": 0, "c": "Botanical extract", "a": ["mugwort extract"], "s": "mugwort-extract", "fa": false},
  {"n": "Mushroom Extract", "r": 0, "c": "Botanical extract", "a": ["mushroom extract"], "s": "mushroom-extract", "fa": false},
  {"n": "Myrrh Extract", "r": 0, "c": "Botanical extract", "a": ["myrrh extract"], "s": "myrrh-extract", "fa": false},
  {"n": "N-Acetyl Glucosamine", "r": 0, "c": "Functional", "a": ["n-acetyl glucosamine"], "s": "n-acetyl-glucosamine", "fa": false},
  {"n": "Neem Extract", "r": 0, "c": "Botanical extract", "a": ["neem extract"], "s": "neem-extract", "fa": false},
  {"n": "Nelumbo Nucifera Flower Extract", "r": 0, "c": "Botanical extract", "a": ["nelumbo nucifera flower extract"], "s": "nelumbo-nucifera-flower-extract", "fa": false},
  {"n": "Neroli Extract", "r": 0, "c": "Botanical extract", "a": ["neroli extract"], "s": "neroli-extract", "fa": false},
  {"n": "Nettle Extract", "r": 0, "c": "Botanical extract", "a": ["nettle extract"], "s": "nettle-extract", "fa": false},
  {"n": "Niacinamide", "r": 0, "c": "Active", "a": ["niacinamide", "nicotinamide", "vitamin b3"], "s": "niacinamide", "fa": false},
  {"n": "Nylon-12", "r": 0, "c": "Functional", "a": ["nylon-12"], "s": "nylon-12", "fa": false},
  {"n": "Oak Bark Extract", "r": 0, "c": "Botanical extract", "a": ["oak bark extract"], "s": "oak-bark-extract", "fa": false},
  {"n": "Oat Extract", "r": 0, "c": "Botanical extract", "a": ["oat extract"], "s": "oat-extract", "fa": false},
  {"n": "Olea Europaea Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["olea europaea leaf extract"], "s": "olea-europaea-leaf-extract", "fa": false},
  {"n": "Oligopeptide-1", "r": 0, "c": "Functional", "a": ["oligopeptide-1"], "s": "oligopeptide-1", "fa": false},
  {"n": "Olive Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["olive leaf extract"], "s": "olive-leaf-extract", "fa": false},
  {"n": "Opuntia Ficus-Indica Extract", "r": 0, "c": "Botanical extract", "a": ["opuntia ficus-indica extract"], "s": "opuntia-ficus-indica-extract", "fa": false},
  {"n": "Orange Blossom Water", "r": 0, "c": "Botanical extract", "a": ["orange blossom water"], "s": "orange-blossom-water", "fa": false},
  {"n": "Oregano Extract", "r": 0, "c": "Botanical extract", "a": ["oregano extract"], "s": "oregano-extract", "fa": false},
  {"n": "Oryza Sativa Bran Extract", "r": 0, "c": "Botanical extract", "a": ["oryza sativa bran extract"], "s": "oryza-sativa-bran-extract", "fa": false},
  {"n": "PCA", "r": 0, "c": "Functional", "a": ["pca"], "s": "pca", "fa": false},
  {"n": "Palmitoyl Hexapeptide-12", "r": 0, "c": "Functional", "a": ["palmitoyl hexapeptide-12"], "s": "palmitoyl-hexapeptide-12", "fa": false},
  {"n": "Palmitoyl Pentapeptide-4", "r": 0, "c": "Functional", "a": ["palmitoyl pentapeptide-4"], "s": "palmitoyl-pentapeptide-4", "fa": false},
  {"n": "Palmitoyl Tripeptide-1", "r": 0, "c": "Functional", "a": ["palmitoyl tripeptide-1"], "s": "palmitoyl-tripeptide-1", "fa": false},
  {"n": "Palmitoyl Tripeptide-5", "r": 0, "c": "Functional", "a": ["palmitoyl tripeptide-5"], "s": "palmitoyl-tripeptide-5", "fa": false},
  {"n": "Panax Ginseng Root Extract", "r": 0, "c": "Botanical extract", "a": ["panax ginseng root extract"], "s": "panax-ginseng-root-extract", "fa": false},
  {"n": "Panthenol", "r": 0, "c": "Soothing", "a": ["panthenol", "provitamin b5"], "s": "panthenol", "fa": false},
  {"n": "Papaya Extract", "r": 0, "c": "Botanical extract", "a": ["papaya extract"], "s": "papaya-extract", "fa": false},
  {"n": "Parsley Extract", "r": 0, "c": "Botanical extract", "a": ["parsley extract"], "s": "parsley-extract", "fa": false},
  {"n": "Peach Extract", "r": 0, "c": "Botanical extract", "a": ["peach extract"], "s": "peach-extract", "fa": false},
  {"n": "Pear Extract", "r": 0, "c": "Botanical extract", "a": ["pear extract"], "s": "pear-extract", "fa": false},
  {"n": "Pentylene Glycol", "r": 0, "c": "Humectant", "a": ["pentylene glycol"], "s": "pentylene-glycol", "fa": false},
  {"n": "Peppermint Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["peppermint leaf extract"], "s": "peppermint-leaf-extract", "fa": false},
  {"n": "Perlite", "r": 0, "c": "Functional", "a": ["perlite"], "s": "perlite", "fa": false},
  {"n": "Petrolatum", "r": 0, "c": "Occlusive", "a": ["petrolatum", "petroleum jelly"], "s": "petrolatum", "fa": false},
  {"n": "Phenoxyethanol", "r": 0, "c": "Functional", "a": ["phenoxyethanol"], "s": "phenoxyethanol", "fa": false},
  {"n": "Phytic Acid", "r": 0, "c": "Functional", "a": ["phytic acid"], "s": "phytic-acid", "fa": false},
  {"n": "Phytic Acid Complex", "r": 0, "c": "Functional", "a": ["phytic acid complex"], "s": "phytic-acid-complex", "fa": false},
  {"n": "Pine Bark Extract", "r": 0, "c": "Botanical extract", "a": ["pine bark extract"], "s": "pine-bark-extract", "fa": false},
  {"n": "Pineapple Extract", "r": 0, "c": "Botanical extract", "a": ["pineapple extract"], "s": "pineapple-extract", "fa": false},
  {"n": "Pinus Pinaster Bark Extract", "r": 0, "c": "Botanical extract", "a": ["pinus pinaster bark extract"], "s": "pinus-pinaster-bark-extract", "fa": false},
  {"n": "Plantain Extract", "r": 0, "c": "Botanical extract", "a": ["plantain extract"], "s": "plantain-extract", "fa": false},
  {"n": "Polyacrylate Crosspolymer-6", "r": 0, "c": "Functional", "a": ["polyacrylate crosspolymer-6"], "s": "polyacrylate-crosspolymer-6", "fa": false},
  {"n": "Polyethylene", "r": 0, "c": "Functional", "a": ["polyethylene"], "s": "polyethylene", "fa": false},
  {"n": "Polyglutamic Acid", "r": 0, "c": "Functional", "a": ["polyglutamic acid"], "s": "polyglutamic-acid", "fa": false},
  {"n": "Polyhydroxy Acid", "r": 0, "c": "Functional", "a": ["polyhydroxy acid"], "s": "polyhydroxy-acid", "fa": false},
  {"n": "Polymethylsilsesquioxane", "r": 0, "c": "Functional", "a": ["polymethylsilsesquioxane"], "s": "polymethylsilsesquioxane", "fa": false},
  {"n": "Polyquaternium-10", "r": 0, "c": "Functional", "a": ["polyquaternium-10"], "s": "polyquaternium-10", "fa": false},
  {"n": "Polysorbate 20", "r": 0, "c": "Emulsifier", "a": ["polysorbate 20"], "s": "polysorbate-20", "fa": true},
  {"n": "Pomegranate Extract", "r": 0, "c": "Botanical extract", "a": ["pomegranate extract"], "s": "pomegranate-extract", "fa": false},
  {"n": "Potassium Chloride", "r": 0, "c": "Functional", "a": ["potassium chloride"], "s": "potassium-chloride", "fa": false},
  {"n": "Potassium Sorbate", "r": 0, "c": "Functional", "a": ["potassium sorbate"], "s": "potassium-sorbate", "fa": false},
  {"n": "Propanediol", "r": 0, "c": "Functional", "a": ["propanediol"], "s": "propanediol", "fa": false},
  {"n": "Propolis Extract", "r": 0, "c": "Botanical extract", "a": ["propolis extract"], "s": "propolis-extract", "fa": false},
  {"n": "Propylene Glycol", "r": 0, "c": "Humectant", "a": ["propylene glycol"], "s": "propylene-glycol", "fa": false},
  {"n": "Propylparaben", "r": 0, "c": "Functional", "a": ["propylparaben"], "s": "propylparaben", "fa": false},
  {"n": "Pullulan", "r": 0, "c": "Functional", "a": ["pullulan"], "s": "pullulan", "fa": false},
  {"n": "Pumpkin Extract", "r": 0, "c": "Botanical extract", "a": ["pumpkin extract"], "s": "pumpkin-extract", "fa": false},
  {"n": "Punica Granatum Extract", "r": 0, "c": "Botanical extract", "a": ["punica granatum extract"], "s": "punica-granatum-extract", "fa": false},
  {"n": "Pyridoxine", "r": 0, "c": "Functional", "a": ["pyridoxine"], "s": "pyridoxine", "fa": false},
  {"n": "Pyrus Malus Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["pyrus malus fruit extract"], "s": "pyrus-malus-fruit-extract", "fa": false},
  {"n": "Raspberry Extract", "r": 0, "c": "Botanical extract", "a": ["raspberry extract"], "s": "raspberry-extract", "fa": false},
  {"n": "Red Clover Extract", "r": 0, "c": "Botanical extract", "a": ["red clover extract"], "s": "red-clover-extract", "fa": false},
  {"n": "Reishi Mushroom Extract", "r": 0, "c": "Botanical extract", "a": ["reishi mushroom extract"], "s": "reishi-mushroom-extract", "fa": false},
  {"n": "Resveratrol", "r": 0, "c": "Botanical extract", "a": ["resveratrol"], "s": "resveratrol", "fa": false},
  {"n": "Riboflavin", "r": 0, "c": "Functional", "a": ["riboflavin"], "s": "riboflavin", "fa": false},
  {"n": "Rice Extract", "r": 0, "c": "Botanical extract", "a": ["rice extract"], "s": "rice-extract", "fa": false},
  {"n": "Rooibos Extract", "r": 0, "c": "Botanical extract", "a": ["rooibos extract"], "s": "rooibos-extract", "fa": false},
  {"n": "Rosa Damascena Flower Extract", "r": 0, "c": "Botanical extract", "a": ["rosa damascena flower extract"], "s": "rosa-damascena-flower-extract", "fa": false},
  {"n": "Rose Extract", "r": 0, "c": "Botanical extract", "a": ["rose extract"], "s": "rose-extract", "fa": false},
  {"n": "Rose Water", "r": 0, "c": "Botanical extract", "a": ["rose water"], "s": "rose-water", "fa": false},
  {"n": "Rosemary Extract", "r": 0, "c": "Botanical extract", "a": ["rosemary extract"], "s": "rosemary-extract", "fa": false},
  {"n": "Rosmarinus Officinalis Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["rosmarinus officinalis leaf extract"], "s": "rosmarinus-officinalis-leaf-extract", "fa": false},
  {"n": "Royal Jelly Extract", "r": 0, "c": "Botanical extract", "a": ["royal jelly extract"], "s": "royal-jelly-extract", "fa": false},
  {"n": "Saccharomyces Ferment", "r": 0, "c": "Botanical extract", "a": ["saccharomyces ferment"], "s": "saccharomyces-ferment", "fa": true},
  {"n": "Safflower Oil", "r": 0, "c": "Oil", "a": ["carthamus tinctorius seed oil", "safflower oil"], "s": "safflower-oil", "fa": true},
  {"n": "Sage Extract", "r": 0, "c": "Botanical extract", "a": ["sage extract"], "s": "sage-extract", "fa": false},
  {"n": "Salicylic Acid", "r": 0, "c": "Active", "a": ["bha", "salicylic acid"], "s": "salicylic-acid", "fa": false},
  {"n": "Salix Alba Bark Extract", "r": 0, "c": "Botanical extract", "a": ["salix alba bark extract"], "s": "salix-alba-bark-extract", "fa": false},
  {"n": "Salvia Officinalis Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["salvia officinalis leaf extract"], "s": "salvia-officinalis-leaf-extract", "fa": false},
  {"n": "Sambucus Nigra Flower Extract", "r": 0, "c": "Botanical extract", "a": ["sambucus nigra flower extract"], "s": "sambucus-nigra-flower-extract", "fa": false},
  {"n": "Sandalwood Extract", "r": 0, "c": "Botanical extract", "a": ["sandalwood extract"], "s": "sandalwood-extract", "fa": false},
  {"n": "Sclerotium Gum", "r": 0, "c": "Thickener", "a": ["sclerotium gum"], "s": "sclerotium-gum", "fa": false},
  {"n": "Sea Buckthorn Extract", "r": 0, "c": "Botanical extract", "a": ["sea buckthorn extract"], "s": "sea-buckthorn-extract", "fa": false},
  {"n": "Sea Kelp Extract", "r": 0, "c": "Botanical extract", "a": ["sea kelp extract"], "s": "sea-kelp-extract", "fa": false},
  {"n": "Sea Salt Extract", "r": 0, "c": "Botanical extract", "a": ["sea salt extract"], "s": "sea-salt-extract", "fa": false},
  {"n": "Seawater", "r": 0, "c": "Botanical extract", "a": ["seawater"], "s": "seawater", "fa": false},
  {"n": "Shea Butter", "r": 0, "c": "Butter", "a": ["butyrospermum parkii butter", "shea butter"], "s": "shea-butter", "fa": true},
  {"n": "Shiitake Extract", "r": 0, "c": "Botanical extract", "a": ["shiitake extract"], "s": "shiitake-extract", "fa": false},
  {"n": "Shikakai Extract", "r": 0, "c": "Botanical extract", "a": ["shikakai extract"], "s": "shikakai-extract", "fa": false},
  {"n": "Silica", "r": 0, "c": "Mineral", "a": ["silica"], "s": "silica", "fa": false},
  {"n": "Silk Protein", "r": 0, "c": "Botanical extract", "a": ["silk protein"], "s": "silk-protein", "fa": false},
  {"n": "Snail Secretion Filtrate", "r": 0, "c": "Botanical extract", "a": ["snail secretion filtrate"], "s": "snail-secretion-filtrate", "fa": false},
  {"n": "Snow Mushroom Extract", "r": 0, "c": "Botanical extract", "a": ["snow mushroom extract"], "s": "snow-mushroom-extract", "fa": false},
  {"n": "Sodium Acetylated Hyaluronate", "r": 0, "c": "Functional", "a": ["sodium acetylated hyaluronate"], "s": "sodium-acetylated-hyaluronate", "fa": false},
  {"n": "Sodium Anisate", "r": 0, "c": "Functional", "a": ["sodium anisate"], "s": "sodium-anisate", "fa": false},
  {"n": "Sodium Ascorbyl Phosphate", "r": 0, "c": "Functional", "a": ["sodium ascorbyl phosphate"], "s": "sodium-ascorbyl-phosphate", "fa": false},
  {"n": "Sodium Benzoate", "r": 0, "c": "Functional", "a": ["sodium benzoate"], "s": "sodium-benzoate", "fa": false},
  {"n": "Sodium Chloride", "r": 0, "c": "Misc", "a": ["sea salt", "sodium chloride"], "s": "sodium-chloride", "fa": false},
  {"n": "Sodium Citrate", "r": 0, "c": "Functional", "a": ["sodium citrate"], "s": "sodium-citrate", "fa": false},
  {"n": "Sodium Cocoyl Glycinate", "r": 0, "c": "Functional", "a": ["sodium cocoyl glycinate"], "s": "sodium-cocoyl-glycinate", "fa": false},
  {"n": "Sodium Cocoyl Isethionate", "r": 0, "c": "Functional", "a": ["sodium cocoyl isethionate"], "s": "sodium-cocoyl-isethionate", "fa": false},
  {"n": "Sodium Gluconate", "r": 0, "c": "Functional", "a": ["sodium gluconate"], "s": "sodium-gluconate", "fa": false},
  {"n": "Sodium Hyaluronate Crosspolymer", "r": 0, "c": "Functional", "a": ["sodium hyaluronate crosspolymer"], "s": "sodium-hyaluronate-crosspolymer", "fa": false},
  {"n": "Sodium Hydroxide", "r": 0, "c": "Functional", "a": ["sodium hydroxide"], "s": "sodium-hydroxide", "fa": false},
  {"n": "Sodium Lactate", "r": 0, "c": "Functional", "a": ["sodium lactate"], "s": "sodium-lactate", "fa": false},
  {"n": "Sodium Lauroyl Lactylate", "r": 0, "c": "Functional", "a": ["sodium lauroyl lactylate"], "s": "sodium-lauroyl-lactylate", "fa": false},
  {"n": "Sodium Lauroyl Sarcosinate", "r": 0, "c": "Functional", "a": ["sodium lauroyl sarcosinate"], "s": "sodium-lauroyl-sarcosinate", "fa": false},
  {"n": "Sodium Levulinate", "r": 0, "c": "Functional", "a": ["sodium levulinate"], "s": "sodium-levulinate", "fa": false},
  {"n": "Sodium Metabisulfite", "r": 0, "c": "Functional", "a": ["sodium metabisulfite"], "s": "sodium-metabisulfite", "fa": false},
  {"n": "Sodium Methyl Cocoyl Taurate", "r": 0, "c": "Functional", "a": ["sodium methyl cocoyl taurate"], "s": "sodium-methyl-cocoyl-taurate", "fa": false},
  {"n": "Sodium PCA", "r": 0, "c": "Humectant", "a": ["sodium pca"], "s": "sodium-pca", "fa": false},
  {"n": "Sodium Phytate", "r": 0, "c": "Functional", "a": ["sodium phytate"], "s": "sodium-phytate", "fa": false},
  {"n": "Sodium Polyglutamate", "r": 0, "c": "Functional", "a": ["sodium polyglutamate"], "s": "sodium-polyglutamate", "fa": false},
  {"n": "Sodium Silicate", "r": 0, "c": "Functional", "a": ["sodium silicate"], "s": "sodium-silicate", "fa": false},
  {"n": "Sodium Starch Octenylsuccinate", "r": 0, "c": "Functional", "a": ["sodium starch octenylsuccinate"], "s": "sodium-starch-octenylsuccinate", "fa": false},
  {"n": "Sodium Sulfite", "r": 0, "c": "Functional", "a": ["sodium sulfite"], "s": "sodium-sulfite", "fa": false},
  {"n": "Solanum Lycopersicum Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["solanum lycopersicum fruit extract"], "s": "solanum-lycopersicum-fruit-extract", "fa": false},
  {"n": "Sorbic Acid", "r": 0, "c": "Functional", "a": ["sorbic acid"], "s": "sorbic-acid", "fa": false},
  {"n": "Sorbitol", "r": 0, "c": "Humectant", "a": ["sorbitol"], "s": "sorbitol", "fa": false},
  {"n": "Soy Extract", "r": 0, "c": "Botanical extract", "a": ["soy extract"], "s": "soy-extract", "fa": false},
  {"n": "Spearmint Leaf Extract", "r": 0, "c": "Botanical extract", "a": ["spearmint leaf extract"], "s": "spearmint-leaf-extract", "fa": false},
  {"n": "Spinach Extract", "r": 0, "c": "Botanical extract", "a": ["spinach extract"], "s": "spinach-extract", "fa": false},
  {"n": "Spirulina Extract", "r": 0, "c": "Botanical extract", "a": ["spirulina extract"], "s": "spirulina-extract", "fa": false},
  {"n": "St. Johns Wort Extract", "r": 0, "c": "Botanical extract", "a": ["st. johns wort extract"], "s": "st-johns-wort-extract", "fa": false},
  {"n": "Strawberry Extract", "r": 0, "c": "Botanical extract", "a": ["strawberry extract"], "s": "strawberry-extract", "fa": false},
  {"n": "Sucrose", "r": 0, "c": "Functional", "a": ["sucrose"], "s": "sucrose", "fa": false},
  {"n": "Sunflower Oil", "r": 0, "c": "Oil", "a": ["helianthus annuus seed oil", "sunflower oil"], "s": "sunflower-oil", "fa": true},
  {"n": "Tapioca Starch", "r": 0, "c": "Functional", "a": ["tapioca starch"], "s": "tapioca-starch", "fa": false},
  {"n": "Taraxacum Officinale Extract", "r": 0, "c": "Botanical extract", "a": ["taraxacum officinale extract"], "s": "taraxacum-officinale-extract", "fa": false},
  {"n": "Tartaric Acid", "r": 0, "c": "Functional", "a": ["tartaric acid"], "s": "tartaric-acid", "fa": false},
  {"n": "Tetrasodium EDTA", "r": 0, "c": "Functional", "a": ["tetrasodium edta"], "s": "tetrasodium-edta", "fa": false},
  {"n": "Tetrasodium Glutamate Diacetate", "r": 0, "c": "Functional", "a": ["tetrasodium glutamate diacetate"], "s": "tetrasodium-glutamate-diacetate", "fa": false},
  {"n": "Thiamine", "r": 0, "c": "Functional", "a": ["thiamine"], "s": "thiamine", "fa": false},
  {"n": "Thyme Extract", "r": 0, "c": "Botanical extract", "a": ["thyme extract"], "s": "thyme-extract", "fa": false},
  {"n": "Tiger Grass Extract", "r": 0, "c": "Botanical extract", "a": ["tiger grass extract"], "s": "tiger-grass-extract", "fa": false},
  {"n": "Tocopheryl Acetate", "r": 0, "c": "Functional", "a": ["tocopheryl acetate"], "s": "tocopheryl-acetate", "fa": true},
  {"n": "Tomato Extract", "r": 0, "c": "Botanical extract", "a": ["tomato extract"], "s": "tomato-extract", "fa": false},
  {"n": "Tranexamic Acid", "r": 0, "c": "Functional", "a": ["tranexamic acid"], "s": "tranexamic-acid", "fa": false},
  {"n": "Trehalose", "r": 0, "c": "Humectant", "a": ["trehalose"], "s": "trehalose", "fa": false},
  {"n": "Tremella Fuciformis Extract", "r": 0, "c": "Botanical extract", "a": ["tremella fuciformis extract"], "s": "tremella-fuciformis-extract", "fa": false},
  {"n": "Triethanolamine", "r": 0, "c": "Functional", "a": ["triethanolamine"], "s": "triethanolamine", "fa": false},
  {"n": "Tripeptide-1", "r": 0, "c": "Functional", "a": ["tripeptide-1"], "s": "tripeptide-1", "fa": false},
  {"n": "Trisodium Ethylenediamine Disuccinate", "r": 0, "c": "Functional", "a": ["trisodium ethylenediamine disuccinate"], "s": "trisodium-ethylenediamine-disuccinate", "fa": false},
  {"n": "Turmeric Extract", "r": 0, "c": "Botanical extract", "a": ["turmeric extract"], "s": "turmeric-extract", "fa": false},
  {"n": "Ubiquinone", "r": 0, "c": "Functional", "a": ["ubiquinone"], "s": "ubiquinone", "fa": false},
  {"n": "Urea", "r": 0, "c": "Humectant", "a": ["urea"], "s": "urea", "fa": false},
  {"n": "Urtica Dioica Extract", "r": 0, "c": "Botanical extract", "a": ["urtica dioica extract"], "s": "urtica-dioica-extract", "fa": false},
  {"n": "Vaccinium Myrtillus Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["vaccinium myrtillus fruit extract"], "s": "vaccinium-myrtillus-fruit-extract", "fa": false},
  {"n": "Vanilla Extract", "r": 0, "c": "Botanical extract", "a": ["vanilla extract"], "s": "vanilla-extract", "fa": false},
  {"n": "Vitis Vinifera Fruit Extract", "r": 0, "c": "Botanical extract", "a": ["vitis vinifera fruit extract"], "s": "vitis-vinifera-fruit-extract", "fa": false},
  {"n": "Water", "r": 0, "c": "Solvent", "a": ["aqua", "eau", "water"], "s": "water", "fa": false},
  {"n": "Watermelon Extract", "r": 0, "c": "Botanical extract", "a": ["watermelon extract"], "s": "watermelon-extract", "fa": false},
  {"n": "Wheat Protein", "r": 0, "c": "Botanical extract", "a": ["wheat protein"], "s": "wheat-protein", "fa": false},
  {"n": "White Tea Extract", "r": 0, "c": "Botanical extract", "a": ["white tea extract"], "s": "white-tea-extract", "fa": false},
  {"n": "Willow Bark Extract", "r": 0, "c": "Botanical extract", "a": ["willow bark extract"], "s": "willow-bark-extract", "fa": false},
  {"n": "Witch Hazel", "r": 0, "c": "Botanical extract", "a": ["witch hazel"], "s": "witch-hazel", "fa": false},
  {"n": "Xanthan Gum", "r": 0, "c": "Thickener", "a": ["xanthan gum"], "s": "xanthan-gum", "fa": false},
  {"n": "Yarrow Extract", "r": 0, "c": "Botanical extract", "a": ["yarrow extract"], "s": "yarrow-extract", "fa": false},
  {"n": "Yeast Extract", "r": 0, "c": "Botanical extract", "a": ["yeast extract"], "s": "yeast-extract", "fa": false},
  {"n": "Yerba Mate Extract", "r": 0, "c": "Botanical extract", "a": ["yerba mate extract"], "s": "yerba-mate-extract", "fa": false},
  {"n": "Zinc Gluconate", "r": 0, "c": "Functional", "a": ["zinc gluconate"], "s": "zinc-gluconate", "fa": false},
  {"n": "Zinc PCA", "r": 0, "c": "Functional", "a": ["zinc pca"], "s": "zinc-pca", "fa": false},
  {"n": "Zinc Stearate", "r": 0, "c": "Functional", "a": ["zinc stearate"], "s": "zinc-stearate", "fa": true},
  {"n": "Zinc Sulfate", "r": 0, "c": "Functional", "a": ["zinc sulfate"], "s": "zinc-sulfate", "fa": false},
  {"n": "Zingiber Officinale Root Extract", "r": 0, "c": "Botanical extract", "a": ["zingiber officinale root extract"], "s": "zingiber-officinale-root-extract", "fa": false},
  {"n": "p-Anisic Acid", "r": 0, "c": "Functional", "a": ["p-anisic acid"], "s": "p-anisic-acid", "fa": false}
];

const lookup = {};
DB.forEach(item => item.a.forEach(al => lookup[al] = item));
function normalize(s){return s.toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9&/\-\s]/g,' ').replace(/\s+/g,' ').trim();}
function parseList(raw){return raw.split(/[,;\n•·]+/).map(x=>x.trim()).filter(Boolean);}
function match(token){
  const norm = normalize(token);
  if(lookup[norm]) return lookup[norm];
  for(const al in lookup){ if(norm === al) return lookup[al]; }
  for(const al in lookup){ if(al.length>5 && norm.includes(al)) return lookup[al]; }
  return null;
}
function pill(r){
  if(r>=3) return '<span class="pill bad">Clogging risk · '+r+'/5</span>';
  if(r>=1) return '<span class="pill low">Low risk · '+r+'/5</span>';
  return '<span class="pill safe">Acne safe · 0/5</span>';
}
function riskText(r){
  if(r>=4) return 'High likelihood of clogging pores — a common breakout trigger for acne-prone skin.';
  if(r===3) return 'Moderate pore-clogging potential; many acne-prone people avoid this.';
  if(r===2) return 'Mild — usually fine, but sensitive skin may want to patch test.';
  if(r===1) return 'Very low risk of clogging pores.';
  return 'Considered non-comedogenic.';
}
function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function checkIngredients(){
  const ta = document.getElementById('ingredients'); const res = document.getElementById('results');
  if(!ta || !res) return; const raw = ta.value;
  if(!raw.trim()){ res.classList.add('hidden'); return; }
  const tokens = parseList(raw); const bad=[], low=[], safe=[], unknown=[]; const seen = new Set();
  tokens.forEach(t=>{ const m = match(t);
    if(m){ if(seen.has(m.n)) return; seen.add(m.n); if(m.r>=3) bad.push(m); else if(m.r>=1) low.push(m); else safe.push(m); }
    else { const key=normalize(t); if(key && !seen.has(key)){ seen.add(key); unknown.push(t.trim()); } } });
  let cls='ok', headline='Looks acne safe', sub='No high-risk pore-clogging ingredients found.';
  if(bad.length){ cls='bad'; headline=bad.length+' pore-clogging ingredient'+(bad.length>1?'s':'')+' found'; sub='These have a comedogenicity rating of 3 or higher.'; }
  else if(low.length){ cls='warn'; headline='Mostly fine — '+low.length+' low-risk ingredient'+(low.length>1?'s':''); sub='Nothing high-risk, but a few mild ones to watch.'; }
  let html = '<div class="score '+cls+'"><div class="big">'+(bad.length||low.length||'✓')+'</div><div><div class="lbl"><strong>'+headline+'</strong></div><div class="muted" style="font-size:13px">'+sub+'</div></div></div>';
  const section = (title, arr) => { if(!arr.length) return ''; let s = '<h3 style="margin:18px 0 4px;font-size:15px">'+title+'</h3>';
    arr.sort((a,b)=>b.r-a.r).forEach(m=>{ s += '<div class="flag"><div><div class="name">'+m.n+'</div><div class="why">'+riskText(m.r)+'</div></div>'+pill(m.r)+'</div>'; }); return s; };
  html += section('🔴 Pore-clogging risk', bad); html += section('🟡 Low risk', low); html += section('🟢 Acne safe', safe);
  if(unknown.length){ html += '<h3 style="margin:18px 0 4px;font-size:15px">⚪ Not in database ('+unknown.length+')</h3>';
    html += '<p class="muted" style="font-size:13px">Not on common pore-clogging lists — not necessarily safe or unsafe: '+unknown.map(u=>escapeHtml(u)).join(', ')+'</p>'; }
  res.innerHTML = html; res.classList.remove('hidden'); res.scrollIntoView({behavior:'smooth', block:'start'});
}
function clearAll(){const ta=document.getElementById('ingredients');if(ta)ta.value='';const r=document.getElementById('results');if(r)r.classList.add('hidden');}
function loadSample(){ const ta=document.getElementById('ingredients'); if(!ta) return;
  ta.value="Water, Glycerin, Coconut Oil, Niacinamide, Isopropyl Myristate, Cocoa Butter, Hyaluronic Acid, Squalane, Cetyl Alcohol, Tocopherol, Algae Extract, Fragrance"; checkIngredients(); }
function checkFungal(){
  const ta = document.getElementById('ingredients'); const res = document.getElementById('results');
  if(!ta || !res) return; const raw = ta.value; if(!raw.trim()){ res.classList.add('hidden'); return; }
  const tokens = parseList(raw); const bad=[], safe=[], unknown=[]; const seen=new Set();
  tokens.forEach(t=>{ const m=match(t);
    if(m){ if(seen.has(m.n)) return; seen.add(m.n); if(m.fa) bad.push(m); else safe.push(m); }
    else { const k=normalize(t); if(k && !seen.has(k)){ seen.add(k); unknown.push(t.trim()); } } });
  const cls = bad.length ? 'bad' : 'ok';
  const headline = bad.length ? (bad.length+' possible fungal-acne trigger'+(bad.length>1?'s':'')+' found') : 'No common fungal-acne triggers found';
  const sub = bad.length ? 'These can feed Malassezia yeast (fatty acids C11–C24, many esters, polysorbates, ferments).' : 'No ingredients on common Malassezia-trigger lists.';
  let html = '<div class="score '+cls+'"><div class="big">'+(bad.length||'✓')+'</div><div><div class="lbl"><strong>'+headline+'</strong></div><div class="muted" style="font-size:13px">'+sub+'</div></div></div>';
  const section = (title, arr, trig) => { if(!arr.length) return ''; let s='<h3 style="margin:18px 0 4px;font-size:15px">'+title+'</h3>';
    arr.sort((a,b)=>a.n.localeCompare(b.n)).forEach(m=>{ s+='<div class="flag"><div><div class="name">'+m.n+'</div><div class="why">'+(trig?'Can feed Malassezia — avoid if you have fungal acne.':'Not a common fungal-acne trigger.')+'</div></div>'+(trig?'<span class="pill bad">FA trigger</span>':'<span class="pill safe">FA safe</span>')+'</div>'; }); return s; };
  html += section('🔴 Possible fungal-acne triggers', bad, true);
  html += section('🟢 Fungal-acne safe', safe, false);
  if(unknown.length){ html += '<h3 style="margin:18px 0 4px;font-size:15px">⚪ Not in database ('+unknown.length+')</h3><p class="muted" style="font-size:13px">'+unknown.map(u=>escapeHtml(u)).join(', ')+'</p>'; }
  res.innerHTML = html; res.classList.remove('hidden'); res.scrollIntoView({behavior:'smooth', block:'start'});
}
function renderTable(){ const tb = document.getElementById('dbtable'); if(!tb) return;
  const rows = DB.slice().sort((a,b)=> b.r-a.r || a.n.localeCompare(b.n));
  tb.innerHTML = rows.map(m=>'<tr data-name="'+m.n.toLowerCase()+'"><td><a href="/ingredient/'+m.s+'.html">'+m.n+'</a></td><td>'+m.c+'</td><td>'+pill(m.r)+'</td></tr>').join('');
  const c=document.getElementById('count'); if(c) c.textContent = DB.length; }
function filterTable(){ const q = document.getElementById('dbsearch').value.toLowerCase();
  document.querySelectorAll('#dbtable tr').forEach(tr=>{ tr.style.display = tr.getAttribute('data-name').includes(q) ? '' : 'none'; }); }
